apiVersion: v1
kind: Service
metadata:
  name: portfolio
  namespace: erikandreasklokk
spec:
  type: ClusterIP
  selector:
    app: portfolio
  ports:
    - name: web
      port: 80
      targetPort: http