apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: erikandreasklokk

resources:
  - service.yaml
  - http-route.yaml
  - deployment.yaml

configMapGenerator:
  - name: portfolio-config
    namespace: erikandreasklokk
    literals:
      - PORTFOLIO_PORT_NUMBER=8080